# modules/evidence/preservation.py
import hashlib
import json
import zipfile
import io
from datetime import datetime, timezone

def generate_evidence_package(session_data: dict) -> tuple[bytes, str]:
    """
    Creates a cryptographically verified evidence package:
    - case_summary.json  (all scan results)
    - evidence_hashes.txt (SHA-256 of all evidence)
    - submission_guide.txt (step-by-step report filing)
    - chain_of_custody.txt (who created this, when, with what tool)
    """
    timestamp = datetime.now(timezone.utc).isoformat()
    case_id = session_data.get('case_id', f"CS-{datetime.now().strftime('%Y%m%d-%H%M%S')}")
    
    # Create in-memory ZIP
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        
        # 1. Case Summary JSON
        case_json = json.dumps(session_data, indent=2, default=str)
        zf.writestr('case_summary.json', case_json)
        
        # 2. Hash file (for tamper detection)
        case_hash = hashlib.sha256(case_json.encode()).hexdigest()
        hash_content = f"""EVIDENCE INTEGRITY VERIFICATION
================================
Case ID: {case_id}
Generated: {timestamp}
Tool: CyberSahayak v2.0

SHA-256 of case_summary.json:
{case_hash}

How to verify:
  Linux/Mac: sha256sum case_summary.json
  Windows:   certutil -hashfile case_summary.json SHA256

If the hash above does not match, the evidence may have been tampered with.
"""
        zf.writestr('evidence_hashes.txt', hash_content)
        
        # 3. Submission guide
        submission_guide = f"""HOW TO FILE YOUR CYBERCRIME COMPLAINT
======================================
Case ID: {case_id}

IMMEDIATE STEPS:
1. Call 1930 (National Cyber Crime Helpline) — available 24/7
2. Visit: https://cybercrime.gov.in
3. Click "File a Complaint"
4. Select your crime category
5. Upload the case_summary.json from this package as evidence

ATTACH TO YOUR COMPLAINT:
- This entire ZIP file
- Original screenshots (unedited)
- Bank statements showing fraudulent transactions
- Call recordings if available

YOUR RIGHTS:
- You can file an FIR at any police station under IPC/IT Act
- If police refuse, escalate to SP/Commissioner
- Relevant sections: IT Act 66C (identity theft), 66D (cheating by impersonation),
  IPC 420 (cheating), 406 (criminal breach of trust)

IMPORTANT: Do NOT delete original messages/screenshots — police need the originals
"""
        zf.writestr('submission_guide.txt', submission_guide)
        
        # 4. Chain of custody
        custody = f"""CHAIN OF CUSTODY RECORD
========================
Case ID: {case_id}
Creation Time (UTC): {timestamp}
Platform: CyberSahayak v2.0
Analysis Engine: Rule-based + ML + LLM hybrid

This evidence package was automatically generated by CyberSahayak.
No manual modification has been made to the evidence data.
The SHA-256 hash in evidence_hashes.txt was computed at the time of generation.
"""
        zf.writestr('chain_of_custody.txt', custody)
    
    zip_buffer.seek(0)
    return zip_buffer.getvalue(), f"CyberSahayak_Evidence_{case_id}.zip"